[package]
name = "process_csv"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
tokio = { version = "1.45.1", features = ["rt-multi-thread", "macros"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres"] }
anyhow = "1.0.98"
